### ISSUE TITLE
Error running "pnpm run build:css"

### ISSUE THREAD

**Issue by tasslehawk** [space-nuko/ComfyBox#122]
I get the fallowing error when I run it. Thank you in advance.

> pnpm run build:css

> ComfyBox@0.0.1 build:css D:\comfybox\ComfyBox
> pollen -c gradio/js/theme/src/pollen.config.cjs && mv src/pollen.css node_modules/@gradio/theme/src

'mv' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by JimWang151** [comment]
> I get the fallowing error when I run it. Thank you in advance.
> 
> > pnpm run build:css
> 
> > ComfyBox@0.0.1 build:css D:\comfybox\ComfyBox
> > pollen -c gradio/js/theme/src/pollen.config.cjs && mv src/pollen.css node_modules/@gradio/theme/src
> 
> 'mv' is not recognized as an internal or external command, operable program or batch file.  ELIFECYCLE  Command failed with exit code 1.  ELIFECYCLE  Command failed with exit code 1.

hello.bro.how you solved this issue?
Thanks for your help.
