### ISSUE TITLE
Not functioning on iPad in safari or chrome 

### ISSUE THREAD

**Issue by halr9000** [space-nuko/ComfyBox#142]
I have this working great on my android phone. However, when trying on my iPad, touches are not registering on some of the controls. For example, cannot select a model, and cannot click on queue.

![B6DC701D-7D73-4FE7-A174-DE0478261251](https://github.com/space-nuko/ComfyBox/assets/18482/d276286d-d10c-40b8-93b3-3de869254a81)
![C95A86AA-8421-4CFA-9AF9-F10D2A5BDB31](https://github.com/space-nuko/ComfyBox/assets/18482/4a7f5c90-d6dd-4c2e-a7a3-eb222a4eb7e3)

**Comment by Katmoget** [comment]
you could try the fix from  https://github.com/space-nuko/ComfyBox/issues/127 , it seems to be a similar issue

**Comment by halr9000** [comment]
> you could try the fix from #127 , it seems to be a similar issue

Ok, interesting. How do I rip out bundled assets?! 😆 So close, yet so far.

**Comment by haze** [comment]
Solved by https://github.com/space-nuko/ComfyBox/pull/148
